### ISSUE TITLE
Website linterhub.com

### ISSUE THREAD

**Issue by romanrostislavovich** [linterhub/www#2]
Need to create a website for linterhub organization. It will be published at `linterhub.com`.

The website comprised of 2 pages: `catalog` and `about us`.

Each page includes: `header`, `body` and `footer`. 
`header` and `footer` don't change on all pages.

`header` include: 
- organization logo, which locates at the upper left
- navigation, which locates at the upper right and includes: `catalog`, `about us` and  `add new linter` (it's static URL: [add new linter][github-issue-linter])

`footer` include the only the copy. 

Pages:
- `catalog` - it's comprised of a table, with search by content and sorting for each of table columns.
Content for table you can get from [this page][bundle]. Table is comprised of following columns: `name`, `description`, `languages` and `license` (priority include)
- `about us` - content is 2 link (without description): link to [organization on github][github-url] and email: `hi@linterhub.com`

as a design is missing, I suggest usage following mockup how an orientation point.
![image](https://user-images.githubusercontent.com/10900467/42031763-1bca5dfe-7ae0-11e8-95e0-53a641ccbc07.png)

[bundle]: https://catalog.linterhub.com/bundle.json
[github-url]: https://github.com/linterhub
[github-issue-linter]: https://github.com/linterhub/catalog/issues/new?template=engine.md

**Comment by xferra** [comment]
Hey @ipin4, any progress on this?
